
title: Design Thinking Phase One - Empathize
description: Design Thinking is a human-centric approach to creating solutions.  This course will teach you the principles of Design Thinking and walk you through appling the first phase, empathize, to your projects. 
template:
  name: design-thinking-phase-one-empathy-template
  repo: design-thinking-phase-one-empathy-template
before:
- type: createIssue
  title: Welcome
  body: 00_welcome.md
- type: updateBranchProtection

# Course artifacts:
# 1. Issue: Welcome
# 2. PR: Repository ownership and names
# 3. PR: Create discoverable repos
# 4. PR: Issue and PR templates
# 5. PR: Workflows
# 6. PR: Managing projects on GitHub
# 7. PR: Measuring success
# 8: Issue: Publish your toolkit
# Course artifacts:
# 1. Issue: Welcome
# 2. PR: Repository ownership and names
# 3. PR: Create discoverable repos
# 4. PR: Issue and PR templates
# 5. PR: Workflows
# 6. PR: Managing projects on GitHub
# 7. PR: Measuring success
# 8: Issue: Publish your toolkit

steps:

#1
- title: Answer your first challenge question
  description: Determine the focus of Design Thinking.
  # what we expect the learner to do
  link: '{{ repoUrl }}/issues/1'
  event: issues.edited #answer the question
  # prepping the learner for the NEXT step
  actions:
  - type: createPullRequest
    title: Introduction to Design Thinking
    head: intro-dt
    body: 01_intro-design-thinking.md
    action_id: introPR
  # how we validate that the learner did it right
  - type: respond
    with: 01_technology-answer.md
    data: 
      url: '%actions.introPR.data.html_url%'
  - type: closeIssue

#2
- title: Answer the ownership challenge
  description: Discover the three categories of interest in Design Thinking.
  link: '{{ repoUrl }}/pull/2'
  event: pull_request.edited
  actions:
  - type: removeBranchProtection
    required: false
  - type: respond
    with: 02_intro-answer.md # this should have my first PR in it


