
title: Design Thinking Phase One - Empathize
description: Design Thinking is a human-centric approach to creating solutions.  This course will teach you the principles of Design Thinking and walk you through applying the first phase, empathize, to your projects. 
template:
  name: design-thinking-phase-one-empathy
  repo: design-thinking-phase-one-empathy-template
before:
- type: createIssue
  title: Welcome
  body: 00_welcome.md
- type: updateBranchProtection

# Course artifacts:
# 1. Issue: Welcome
# 2. PR: Intro to Design Thinking
# 3. PR: Five Phases
# 4. PR: Empathy
# 5: Issue: Publish your toolkit

steps:

#1
- title: Answer your first challenge question
  description: Determine the focus of Design Thinking.
  # what we expect the learner to do
  link: '{{ repoUrl }}/issues/1'
  event: issues.edited #answer the question
  # prepping the learner for the NEXT step
  actions:
  - type: createPullRequest
    title: Intro to Design Thinking
    head: intro-dt
    body: 01_intro-design-thinking.md
    action_id: introPR
  # how we validate that the learner did it right
  - type: respond
    with: 01_technology-answer.md
    data: 
      url: '%actions.introPR.data.html_url%'
  - type: closeIssue

#2
- title: Answer the MVP challenge
  description: Discover the definition of MVP and the three important considerations in Design Thinking.
  link: '{{ repoUrl }}/pull/2'
  event: pull_request.edited
  actions:
  - type: removeBranchProtection
    required: false
  - type: respond
    with: 02_intro-answer.md # this has the first PR in it

#3
- title: Merge the MVP pull request
  description: Beef up your Design Thinking toolkit with resources about Minimum Viable Product.
  link: '{{ repoUrl }}/pull/2'
  event: pull_request.closed
  actions:
  - type: updateBranchProtection
    required: false
  - type: createPullRequest
    title: The three principles of Design Thinking
    head: three-principles
    body: 03_three-principles.md
    action_id: principlesPR
  - type: respond
    with: goto-pr.md
    data:
      url: '%actions.principlesPR.data.html_url%'  


#6
# - title: Enable GitHub Pages
#   description: Publish your Design Thinking toolkit by turning on GitHub Pages. 
#   link: '{{ repoUrl }}/pull/8'
#   event: page_build
#   actions:
#   - type: removeBranchProtection
#     required: false
#   - type: octokit
#     method: repos.getPages
#     owner: '%payload.repository.owner.login%'
#     repo: '%payload.repository.name%'
#     action_id: pagesUrl
#   - type: respond
#     issue: Publish your toolkit
#     with: 14_congratulations.md
#     data:
#       deploymentURL: '%actions.pagesUrl.data.html_url%'
#       learningPathURL: 'https://lab.github.com/githubtraining/paths/innersource:-theory-to-practice'
#       forkURL: '%payload.repository.html_url%/fork'
#       downloadURL: '%payload.repository.html_url%/archive/master.zip'


