title: "Design Thinking: Phase One - Empathize"
tagline: Learn how to use the first phase of Design Thinking, Empathize, to create innovative solutions for your projects.
description: >-
  Design Thinking is a human-centric approach to creating solutions.  This course will teach you the principles of Design Thinking and walk you through how to apply the first phase, empathize, to your projects.
template:
  repo: design-thinking-phase-one-empathy-template
  name: design-thinking-phase-one-empathy

#  preferences:
#  - type: radio
#    name: teamRole
#    label: Select your role
#    description: Select your role to see tailored content.
#    options:
#      - label: Developer
#        value: dev
#      - label: Project Manager
#        value: pm
#      - label: No specific role
#        value: all
#        selected: true

before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome!
    body: welcome-issue.md
    comments:
    - turn-on-gh-pages.md
steps:
  # 1
  - title: Turn on GitHub Pages
    description: Turn on GitHub Pages in the settings page of the repository.
    event: page_build
    link: '{{ repoUrl }}/issues/1'
    actions:
    - type: octokit
      method: repos.getPages
      owner: '%payload.repository.owner.login%'
      repo: '%payload.repository.name%'
      action_id: pagesUrl
    - type: respond
      issue: Design Thinking: Phase One - Empathy
      with: close-issue.md
      data:
        pagesUrl: '%actions.pagesUrl.data.html_url%'

  # 2
