title: "Design Thinking Phase One - Empathize"
description: Design Thinking is a human-centric approach to creating solutions.  This course will teach you the principles of Design Thinking and walk you through appling the first phase, empathize, to your projects.
template:
  repo: design-thinking-phase-one-empathy-template
  name: design-thinking-phase-one-empathy

#  preferences:
#  - type: radio
#    name: teamRole
#    label: Select your role
#    description: Select your role to see tailored content.
#    options:
#      - label: Developer
#        value: dev
#      - label: Project Manager
#        value: pm
#      - label: No specific role
#        value: all
#        selected: true

before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome
    body: 00_welcome.md

# Course artifacts:
# 1. Issue: Welcome
# 2. Issue: Intro to Design Thinking
#
#Issue: Publish your toolkit


steps:
  # 1
- title: Answer your first challenge question
  description: Determine the focus of Design Thinking.

  # what we expect the learner to do
  link: '{{ repoUrl }}/issues/1'
  event: issues.edited
  # how we validate that the learner did it right
  actions:
  - type: createIssue
    title: Intro to Design Thinking
    body: intro-design-thinking.md
    action_id: secondIssue
  # prepping the learner for the NEXT step
  - type: respond
    with: 01_design-thinking-technology.md
    data:
      url: '%actions.secondIssue.data.html_url%'
  - type: closeIssue
